"""
USER AGENT - Two Graph Topologies

RegisterUser graph:
    START
      |
      v
  [reason_hash_password]   LLM — given (password, salt), reason through the
      |                    SHA-256(password + salt) computation and return
      |                    the 64-char hex digest.
      v
  [validate_hash]          Deterministic guard — verify the LLM result is
      |                    exactly 64 lowercase hex chars; if not, fall back
      |                    to hashlib.sha256 reference implementation.
      v
  [persist_user]           Deterministic — MongoDB insert_one + Redis cache.
      v
     END

Login graph:
    START
      |
      v
  [fetch_user]             Deterministic — Redis / MongoDB lookup by username.
      v
  [reason_verify_password] LLM — given (password, salt, stored_hash), reason
      |                    whether SHA-256(password + salt) == stored_hash.
      |                    Returns {"match": true|false}.
      v
  [validate_decision]      Deterministic guard — must be boolean; if malformed,
      |                    fall back to hashlib.verify_password reference.
      v
  [issue_token]            Deterministic — generate and return JWT.
      v
     END

GetUserId / ComposeCreator / ComposeCreatorWithUserId:
  No LLM — pure deterministic Redis/MongoDB lookup.
  Implemented directly in the handler (not via LangGraph).

Key Design Decisions
--------------------
- Thrift interface UNCHANGED (all 6 methods).
- MongoDB schema, Redis key layout UNCHANGED.
- password.py is kept as the deterministic fallback reference.
- jwt_helper.py is unchanged — JWT generation is deterministic.
- Token metrics tracked per operation.
"""

import json
import logging
import re
import asyncio
import threading
from typing import TypedDict, Optional, Dict, Any

from langgraph.graph import StateGraph, END
from langchain_ollama import ChatOllama

from pymongo import MongoClient
from pymongo.errors import DuplicateKeyError
import redis as redis_lib

from .password   import generate_salt, hash_password, verify_password
from .jwt_helper import generate_token

logger = logging.getLogger("user-agent")

# ---------------------------------------------------------------------------
# LLM
# ---------------------------------------------------------------------------

llm = ChatOllama(model="llama3.2:3b", temperature=0.0, reasoning=False)

# ---------------------------------------------------------------------------
# Redis cache key prefixes (identical to original handler.py)
# ---------------------------------------------------------------------------

_KEY_USERNAME = "username:"   # username  → user_id  (str)
_KEY_USER_ID  = "userid:"     # user_id   → JSON user doc


# ===========================================================================
# State definitions
# ===========================================================================

class RegisterAgentState(TypedDict):
    # Inputs
    req_id:      int
    first_name:  str
    last_name:   str
    username:    str
    password:    str
    user_id:     int
    salt:        str        # pre-generated by gather_inputs

    # LLM output
    llm_password_hashed: Optional[str]   # 64-char hex from LLM

    # Final (validated)
    password_hashed: Optional[str]       # confirmed 64-char hex

    # Metrics
    total_input_tokens:  int
    total_output_tokens: int
    total_llm_calls:     int
    fallback_used:       bool


class LoginAgentState(TypedDict):
    # Inputs
    req_id:    int
    username:  str
    password:  str
    secret:    str
    jwt_expiry: int

    # After fetch_user
    user_doc:  Optional[Dict]   # full user document from DB

    # LLM output
    llm_match: Optional[bool]   # True/False from LLM

    # Final
    verified:  Optional[bool]   # confirmed boolean
    token:     Optional[str]    # JWT string

    # Metrics
    total_input_tokens:  int
    total_output_tokens: int
    total_llm_calls:     int
    fallback_used:       bool


# ===========================================================================
# Helpers
# ===========================================================================

def _parse_json(text: str) -> Optional[dict]:
    try:
        m = re.search(r"\{.*\}", text, re.DOTALL)
        if m:
            return json.loads(m.group(0))
    except Exception as exc:
        logger.warning("JSON parse error: %s — raw: %r", exc, text[:300])
    return None


def _is_valid_hash(h: Any) -> bool:
    """A valid SHA-256 hex digest is exactly 64 lowercase hex chars."""
    return (
        isinstance(h, str)
        and len(h) == 64
        and re.fullmatch(r"[0-9a-f]{64}", h) is not None
    )


# ===========================================================================
# RegisterUser graph nodes
# ===========================================================================

def make_reason_hash_node():
    """
    Node: reason_hash_password  (LLM)
    Given (password, salt), compute SHA-256(password + salt) hex digest.
    This is the static hashing logic converted to LLM reasoning.
    """
    async def reason_hash_password(state: RegisterAgentState) -> RegisterAgentState:
        password = state["password"]
        salt     = state["salt"]

        prompt = f"""
You are a password hashing agent.

Your task is to compute the SHA-256 hex digest of the concatenation of a
password string and a salt string.

Algorithm:
  1. Concatenate: combined = password + salt  (no separator)
  2. Encode combined as UTF-8 bytes
  3. Compute SHA-256 of those bytes
  4. Return the result as a 64-character lowercase hexadecimal string

Rules:
  - The result MUST be exactly 64 lowercase hexadecimal characters (0-9, a-f)
  - Return ONLY valid JSON — no explanation, no code, no markdown

Schema:
{{
  "password_hashed": "<64-char lowercase hex string>"
}}

Input:
  password = {json.dumps(password)}
  salt     = {json.dumps(salt)}
"""
        logger.info("reason_hash_password LLM call req_id=%d, prompt=%s", state["req_id"], prompt)

        response = await asyncio.to_thread(llm.invoke, prompt)
        raw      = response.text()
        in_tok   = response.usage_metadata.get("input_tokens",  0)
        out_tok  = response.usage_metadata.get("output_tokens", 0)

        logger.info("LLM raw=%r  in=%d out=%d", raw[:100], in_tok, out_tok)
        print(f"[reason_hash_password] raw={raw[:80]!r}  in={in_tok} out={out_tok}")

        parsed = _parse_json(raw)
        llm_hash = None
        if parsed and isinstance(parsed.get("password_hashed"), str):
            llm_hash = parsed["password_hashed"]

        state["llm_password_hashed"]  = llm_hash
        state["total_input_tokens"]  += in_tok
        state["total_output_tokens"] += out_tok
        state["total_llm_calls"]     += 1
        return state
    return reason_hash_password


def make_validate_hash_node():
    """
    Node: validate_hash  (deterministic guard)
    Verify the LLM produced a valid 64-char hex hash.
    Fallback: hashlib reference implementation.
    """
    async def validate_hash(state: RegisterAgentState) -> RegisterAgentState:
        llm_hash = state.get("llm_password_hashed")

        if _is_valid_hash(llm_hash):
            state["password_hashed"] = llm_hash
            state["fallback_used"]   = False
            logger.info("validate_hash PASS req_id=%d", state["req_id"])
            print(f"[validate_hash] PASS")
        else:
            fallback = hash_password(state["password"], state["salt"])
            state["password_hashed"] = fallback
            state["fallback_used"]   = True
            logger.warning(
                "validate_hash FALLBACK req_id=%d llm=%r -> fallback computed",
                state["req_id"], llm_hash,
            )
            print(f"[validate_hash] FALLBACK  llm={llm_hash!r}")

        return state
    return validate_hash


def make_persist_user_node(redis_client: redis_lib.Redis, mongo_col):
    """
    Node: persist_user  (deterministic)
    MongoDB insert_one + Redis cache (both directions).
    Raises on duplicate username — identical to original handler.
    """
    async def persist_user(state: RegisterAgentState) -> RegisterAgentState:
        doc = {
            "user_id":         state["user_id"],
            "first_name":      state["first_name"],
            "last_name":       state["last_name"],
            "username":        state["username"],
            "password_hashed": state["password_hashed"],
            "salt":            state["salt"],
        }

        try:
            mongo_col.insert_one(doc)
        except DuplicateKeyError:
            raise ValueError(f"Username already registered: {state['username']!r}")
        except Exception as exc:
            logger.error("persist_user MongoDB failed: %s", exc)
            raise

        # Redis cache — both directions (matches original handler)
        safe_doc = {k: v for k, v in doc.items() if k != "_id"}
        try:
            redis_client.set(
                _KEY_USERNAME + state["username"], str(state["user_id"])
            )
            redis_client.set(
                _KEY_USER_ID + str(state["user_id"]),
                json.dumps(safe_doc),
            )
        except redis_lib.RedisError as exc:
            logger.warning("persist_user Redis failed: %s", exc)

        logger.info(
            "persist_user OK req_id=%d username=%r user_id=%d",
            state["req_id"], state["username"], state["user_id"],
        )
        print(f"[persist_user] OK  username={state['username']} user_id={state['user_id']}")
        return state
    return persist_user


# ===========================================================================
# Login graph nodes
# ===========================================================================

def make_fetch_user_node(redis_client: redis_lib.Redis, mongo_col):
    """
    Node: fetch_user  (deterministic)
    Retrieve the full user document from Redis → MongoDB.
    """
    async def fetch_user(state: LoginAgentState) -> LoginAgentState:
        username = state["username"]

        # 1. Try username cache → user_id → user doc
        try:
            uid_bytes = redis_client.get(_KEY_USERNAME + username)
            if uid_bytes is not None:
                uid = int(uid_bytes)
                doc_bytes = redis_client.get(_KEY_USER_ID + str(uid))
                if doc_bytes is not None:
                    state["user_doc"] = json.loads(doc_bytes.decode())
                    logger.debug("fetch_user cache HIT username=%r", username)
                    return state
        except Exception as exc:
            logger.warning("fetch_user Redis failed: %s", exc)

        # 2. MongoDB fallback
        try:
            doc = mongo_col.find_one({"username": username})
        except Exception as exc:
            logger.error("fetch_user MongoDB failed: %s", exc)
            state["user_doc"] = None
            return state

        if doc:
            doc.pop("_id", None)
        state["user_doc"] = doc
        if doc:
            # Backfill cache
            try:
                redis_client.set(_KEY_USERNAME + username, str(doc["user_id"]))
                redis_client.set(
                    _KEY_USER_ID + str(doc["user_id"]),
                    json.dumps(doc),
                )
            except Exception:
                pass

        logger.debug("fetch_user MongoDB username=%r found=%s", username, doc is not None)
        return state
    return fetch_user


def make_reason_verify_node():
    """
    Node: reason_verify_password  (LLM)
    Given (password, salt, stored_hash), reason whether
    SHA-256(password + salt) matches stored_hash.
    This is the credential-verification logic converted to LLM reasoning.
    """
    async def reason_verify_password(state: LoginAgentState) -> LoginAgentState:
        doc = state.get("user_doc")
        if doc is None:
            # User not found — no point calling LLM
            state["llm_match"]           = False
            state["total_llm_calls"]    += 1
            return state

        password     = state["password"]
        salt         = doc.get("salt", "")
        stored_hash  = doc.get("password_hashed", "")

        prompt = f"""
You are a password verification agent.

Your task is to determine whether a given password matches a stored SHA-256 hash.

Algorithm:
  1. Concatenate: combined = password + salt  (no separator)
  2. Encode combined as UTF-8 bytes
  3. Compute SHA-256 of those bytes → result_hex (64 lowercase hex chars)
  4. Compare result_hex == stored_hash (exact string match)

Rules:
  - Return true if they match, false otherwise
  - Return ONLY valid JSON — no explanation, no code, no markdown

Schema:
{{
  "match": true | false
}}

Input:
  password    = {json.dumps(password)}
  salt        = {json.dumps(salt)}
  stored_hash = {json.dumps(stored_hash)}
"""

        logger.info("reason_verify_password LLM call req_id=%d, \n prompt=%s", state["req_id"], prompt)

        response = await asyncio.to_thread(llm.invoke, prompt)
        raw      = response.text()
        in_tok   = response.usage_metadata.get("input_tokens",  0)
        out_tok  = response.usage_metadata.get("output_tokens", 0)

        logger.info("LLM raw=%r  in=%d out=%d", raw[:100], in_tok, out_tok)
        print(f"[reason_verify_password] raw={raw!r}  in={in_tok} out={out_tok}")

        parsed   = _parse_json(raw)
        llm_match = None
        if parsed is not None and "match" in parsed:
            val = parsed["match"]
            if isinstance(val, bool):
                llm_match = val
            elif isinstance(val, str):
                llm_match = val.lower() == "true"

        state["llm_match"]            = llm_match
        state["total_input_tokens"]  += in_tok
        state["total_output_tokens"] += out_tok
        state["total_llm_calls"]     += 1
        return state
    return reason_verify_password


def make_validate_decision_node():
    """
    Node: validate_decision  (deterministic guard)
    Verify the LLM returned a valid boolean match.
    Fallback: hashlib verify_password reference.
    """
    async def validate_decision(state: LoginAgentState) -> LoginAgentState:
        doc = state.get("user_doc")
        if doc is None:
            state["verified"]      = False
            state["fallback_used"] = False
            return state

        llm_match = state.get("llm_match")

        if isinstance(llm_match, bool):
            state["verified"]      = llm_match
            state["fallback_used"] = False
            logger.info("validate_decision PASS req_id=%d match=%s",
                        state["req_id"], llm_match)
            print(f"[validate_decision] PASS  match={llm_match}")
        else:
            # Fallback: deterministic reference
            fallback = verify_password(
                state["password"],
                doc.get("salt", ""),
                doc.get("password_hashed", ""),
            )
            state["verified"]      = fallback
            state["fallback_used"] = True
            logger.warning(
                "validate_decision FALLBACK req_id=%d llm=%r -> fallback=%s",
                state["req_id"], llm_match, fallback,
            )
            print(f"[validate_decision] FALLBACK  llm={llm_match!r} -> correct={fallback}")

        return state
    return validate_decision


def make_issue_token_node():
    """
    Node: issue_token  (deterministic)
    Generate JWT if verified, else leave token=None (handler raises SE_UNAUTHORIZED).
    """
    async def issue_token(state: LoginAgentState) -> LoginAgentState:
        if not state.get("verified"):
            state["token"] = None
            return state

        doc = state["user_doc"]
        token = generate_token(
            doc["user_id"],
            doc["username"],
            state["secret"],
            state["jwt_expiry"],
        )
        state["token"] = token
        logger.info(
            "issue_token OK req_id=%d username=%r user_id=%d",
            state["req_id"], doc["username"], doc["user_id"],
        )
        print(f"[issue_token] OK  username={doc['username']}")
        return state
    return issue_token


# ===========================================================================
# Graph builders
# ===========================================================================

def build_register_agent(
    redis_client: redis_lib.Redis,
    mongo_col,
) -> any:
    """Build and compile the RegisterUser LangGraph agent."""
    graph = StateGraph(RegisterAgentState)

    graph.add_node("reason_hash_password", make_reason_hash_node())
    graph.add_node("validate_hash",        make_validate_hash_node())
    graph.add_node("persist_user",         make_persist_user_node(redis_client, mongo_col))

    graph.set_entry_point("reason_hash_password")
    graph.add_edge("reason_hash_password", "validate_hash")
    graph.add_edge("validate_hash",        "persist_user")
    graph.add_edge("persist_user",         END)

    return graph.compile()


def build_login_agent(
    redis_client: redis_lib.Redis,
    mongo_col,
) -> any:
    """Build and compile the Login LangGraph agent."""
    graph = StateGraph(LoginAgentState)

    graph.add_node("fetch_user",             make_fetch_user_node(redis_client, mongo_col))
    graph.add_node("reason_verify_password", make_reason_verify_node())
    graph.add_node("validate_decision",      make_validate_decision_node())
    graph.add_node("issue_token",            make_issue_token_node())

    graph.set_entry_point("fetch_user")
    graph.add_edge("fetch_user",             "reason_verify_password")
    graph.add_edge("reason_verify_password", "validate_decision")
    graph.add_edge("validate_decision",      "issue_token")
    graph.add_edge("issue_token",            END)

    return graph.compile()